# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



jobs:
  - job: image_checks
    displayName: "Image checks"
    pool:
      vmImage: ubuntu-latest
    steps:
      # Docker login goes here (TODO: Deploy registry in container instances)
      - task: trivy@1
        inputs:
          version: 'latest'
          loginDockerConfig: true
          image: '$(repository):$(tag)'
  - job: reject_image
    displayName: "Reject image"
    dependsOn:
      - image_checks
    condition: failed()
    steps:
      - script: echo "Image $(REPOSITORY):$(TAG) will be rejected"
  - job: push_image
    displayName: "Push image"
    dependsOn:
      - image_checks
    condition: succeeded()
    steps:
      - script: echo "Image $(REPOSITORY):$(TAG) will be pushed"