# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



pool:
  vmImage: ubuntu-latest

steps:
  # Docker login goes here (TODO: Deploy registry in container instances)
  - task: trivy@1
    inputs:
      version: 'latest'
      loginDockerConfig: true
      image: '$(repository):$(tag)'
  - ${{ if in(variables['Agent.JobStatus'], 'Succeeded', 'SucceededWithIssues') }}:
    - script: echo "Image $(REPOSITORY):$(TAG) accepted"
  - ${{ else }}:
    - script: echo "Image $(REPOSITORY):$(TAG) rejected"